# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxVHKmr8B1hXrG9IYX6IQ2eWJQZhw7H-
"""

# Step 1: Import necessary modules
import random
import string

# Step 2: Function to generate a random username
def generate_username(include_numbers=True, include_special_chars=False, length=8):
    adjectives = ["Cool", "Happy", "Brave", "Fast", "Clever", "Witty", "Epic", "Mighty", "Lucky"]
    nouns = ["Tiger", "Dragon", "Warrior", "Eagle", "Knight", "Wizard", "Shadow", "Ninja", "Falcon"]

    adj = random.choice(adjectives)
    noun = random.choice(nouns)
    username = adj + noun

    if include_numbers:
        username += str(random.randint(10, 99))

    if include_special_chars:
        username += random.choice(string.punctuation)

    return username[:length]

# Step 3: Function to save usernames to a file
def save_to_file(usernames, filename="generated_usernames.txt"):
    with open(filename, "w") as file:
        for username in usernames:
            file.write(username + "\n")
    print(f"Usernames saved to {filename}")

# Step 4: Main function to handle user interaction
def main():
    print("Welcome to the Random Username Generator!")

    try:
       # Step 5: Get user inputs
        num_usernames = int(input("How many usernames do you want to generate? "))
        include_numbers = input("Include numbers? (yes/no): ").strip().lower() == "yes"
        include_special_chars = input("Include special characters? (yes/no): ").strip().lower() == "yes"
        length = int(input("Enter max length of username (default 8): ") or 8)
        # Step 6: Generate usernames
        usernames = [generate_username(include_numbers, include_special_chars, length) for _ in range(num_usernames)]

        # Step 7: Display generated usernames
        print("\nGenerated Usernames:")
        for username in usernames:
            print(username)

        # Step 8: Ask if the user wants to save the usernames
        save_option = input("Do you want to save these usernames to a file? (yes/no): ").strip().lower()
        if save_option == "yes":
            save_to_file(usernames)

    except ValueError:
        print("Invalid input! Please enter valid values.")

# Step 9: Run the program
if __name__ == "__main__":
    main()

